version: '3'
services:
  # list of microservices
  user:
    build: ./services/user
    networks:
      internal:

  # the gateway should depend on all other services
  gateway:
    build: ./services/gateway
    ports:
      - '4000:3000'
    depends_on:
      - 'user'
    networks:
      internal:

networks:
  internal:
