version: '3'
services:
  # microservices, no need to expose ports since we'll be talking to the gateway
  user:
    build: ./packages/user
    networks:
      internal:

  # the gateway should depend on all other services
  gateway:
    build: ./packages/gateway
    ports:
      - '4000:3000'
    depends_on:
      - 'user'
    networks:
      internal:

networks:
  internal:
