version: '3.7'
services:
  ## microservices. no need to expose ports, the gateway is on the same network
  user:
    build: ./packages/user
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - WAIT_HOSTS=database:5432
    restart: always
    depends_on:
      - database
    networks:
      - internal

  ## shared database. envs come from host, expose port for external access
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '8642:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 15s
      timeout: 10s
      start_period: 10s
    restart: always
    networks:
      - internal

  ## the gateway should depend on all other services
  gateway:
    build: ./packages/gateway
    ports:
      - '4000:3000'
    depends_on:
      - database
      - user
    restart: always
    networks:
      - internal

networks:
  internal:

volumes:
  db:
